/* Generated By:JJTree: Do not edit this line. ASTAddExpr.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY= */
package yapl.compiler;

public class ASTAddExpr extends SimpleNode {
  public ASTAddExpr(int id) {
    super(id);
  }

  public ASTAddExpr(Parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=0098cf16ca7cc7bc150d35f20794c950 (do not edit this line) */
