/* Generated By:JJTree: Do not edit this line. ASTAssignment.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package yapl.compiler;

public
class ASTAssignment extends SimpleNode {
  public ASTAssignment(int id) {
    super(id);
  }

  public ASTAssignment(Parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=905318b71a2b1afe9225dbec5c9269a0 (do not edit this line) */
