/* Generated By:JJTree: Do not edit this line. ASTAddOp.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package yapl.compiler;

public
class ASTAddOp extends SimpleNode {
  public ASTAddOp(int id) {
    super(id);
  }

  public ASTAddOp(Parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=31fbed5f13814c461d706ea158fb9741 (do not edit this line) */
