/* Generated By:JJTree: Do not edit this line. ASTArrayLen.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package yapl.compiler;

public
class ASTArrayLen extends SimpleNode {
  public ASTArrayLen(int id) {
    super(id);
  }

  public ASTArrayLen(Parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=2a796e6a067b7d39cae4357ab0801034 (do not edit this line) */
