/* Generated By:JJTree: Do not edit this line. ASTArgumentList.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY= */
package yapl.compiler;

public class ASTArgumentList extends SimpleNode {
  public ASTArgumentList(int id) {
    super(id);
  }

  public ASTArgumentList(Parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=946a711c8159663d06f61d3fab590ddb (do not edit this line) */
