/* Generated By:JJTree: Do not edit this line. ASTAddOp.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY= */
package yapl.compiler;

public class ASTAddOp extends SimpleNode {
  public ASTAddOp(int id) {
    super(id);
  }

  public ASTAddOp(Parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=a54a317b6baea737cb38be172314c793 (do not edit this line) */
