/* Generated By:JJTree: Do not edit this line. ASTArgumentList.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package yapl.compiler;

public
class ASTArgumentList extends SimpleNode {
  public ASTArgumentList(int id) {
    super(id);
  }

  public ASTArgumentList(Parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=d85b6309c7e461b5716f10b6f0031f64 (do not edit this line) */
