/* Generated By:JJTree: Do not edit this line. ASTArrayLen.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY= */
package yapl.compiler;

public class ASTArrayLen extends SimpleNode {
  public ASTArrayLen(int id) {
    super(id);
  }

  public ASTArrayLen(Parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=c4b476ebd26e035c77aed17555592e46 (do not edit this line) */
