/* Generated By:JJTree: Do not edit this line. ASTAddExpr.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package yapl.compiler;

public
class ASTAddExpr extends SimpleNode {
  public ASTAddExpr(int id) {
    super(id);
  }

  public ASTAddExpr(Parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=37cc3696750cd023910b456a92473129 (do not edit this line) */
