/* Generated By:JJTree: Do not edit this line. ASTCondAndExpr.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package yapl.compiler;

public
class ASTCondAndExpr extends SimpleNode {
  public ASTCondAndExpr(int id) {
    super(id);
  }

  public ASTCondAndExpr(Parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=cb8d46d3016ef118f933a3c589b5aa8c (do not edit this line) */
