/* Generated By:JJTree: Do not edit this line. ASTConstDecl.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY= */
package yapl.compiler;

public class ASTConstDecl extends SimpleNode {
  public ASTConstDecl(int id) {
    super(id);
  }

  public ASTConstDecl(Parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=d3bc38a0993bf405342da690fbf9f322 (do not edit this line) */
