/* Generated By:JJTree: Do not edit this line. ASTConstDecl.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package yapl.compiler;

public
class ASTConstDecl extends SimpleNode {
  public ASTConstDecl(int id) {
    super(id);
  }

  public ASTConstDecl(Parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=6bf338cc759acf81e9d88689beefc17d (do not edit this line) */
