/* Generated By:JJTree: Do not edit this line. ASTCreationExpr.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY= */
package yapl.compiler;

public class ASTCreationExpr extends SimpleNode {
  public ASTCreationExpr(int id) {
    super(id);
  }

  public ASTCreationExpr(Parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=89b9316d4cce3111277f519e9dee08e9 (do not edit this line) */
