/* Generated By:JJTree: Do not edit this line. ASTCondAndExpr.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY= */
package yapl.compiler;

public class ASTCondAndExpr extends SimpleNode {
  public ASTCondAndExpr(int id) {
    super(id);
  }

  public ASTCondAndExpr(Parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=40b76b08af77a02b5be6cea37d06b8d5 (do not edit this line) */
