/* Generated By:JJTree: Do not edit this line. ASTCreationExpr.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package yapl.compiler;

public
class ASTCreationExpr extends SimpleNode {
  public ASTCreationExpr(int id) {
    super(id);
  }

  public ASTCreationExpr(Parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=b173f24f8a880da76cc33a0fbf596cb9 (do not edit this line) */
