/* Generated By:JJTree: Do not edit this line. ASTDecl.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package yapl.compiler;

public
class ASTDecl extends SimpleNode {
  public ASTDecl(int id) {
    super(id);
  }

  public ASTDecl(Parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=34f1d8153307775eba62608505198912 (do not edit this line) */
