/* Generated By:JJTree: Do not edit this line. ASTDecl.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY= */
package yapl.compiler;

public class ASTDecl extends SimpleNode {
  public ASTDecl(int id) {
    super(id);
  }

  public ASTDecl(Parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=0b75366b1926f1904de23290adeed000 (do not edit this line) */
