/* Generated By:JJTree: Do not edit this line. ASTExpr.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY= */
package yapl.compiler;

public class ASTExpr extends SimpleNode {
  public ASTExpr(int id) {
    super(id);
  }

  public ASTExpr(Parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=e77fe407e951c8c4b7fe7d160c2a196b (do not edit this line) */
