/* Generated By:JJTree: Do not edit this line. ASTEqualExpr.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY= */
package yapl.compiler;

public class ASTEqualExpr extends SimpleNode {
  public ASTEqualExpr(int id) {
    super(id);
  }

  public ASTEqualExpr(Parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=e6969eda11c8f87d01662e4c2383a83a (do not edit this line) */
