/* Generated By:JJTree: Do not edit this line. ASTEqualOp.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package yapl.compiler;

public
class ASTEqualOp extends SimpleNode {
  public ASTEqualOp(int id) {
    super(id);
  }

  public ASTEqualOp(Parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=d47be6de5f81a80a20efbec92b78a20f (do not edit this line) */
