/* Generated By:JJTree: Do not edit this line. ASTEnd.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY= */
package yapl.compiler;

public class ASTEnd extends SimpleNode {
  public ASTEnd(int id) {
    super(id);
  }

  public ASTEnd(Parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=6739fc8ce6242101c61c991ae163db63 (do not edit this line) */
