/* Generated By:JJTree: Do not edit this line. ASTEqualExpr.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package yapl.compiler;

public
class ASTEqualExpr extends SimpleNode {
  public ASTEqualExpr(int id) {
    super(id);
  }

  public ASTEqualExpr(Parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=d1ec788917194b9c9fffea5550e62ca7 (do not edit this line) */
