/* Generated By:JJTree: Do not edit this line. ASTEqualOp.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY= */
package yapl.compiler;

public class ASTEqualOp extends SimpleNode {
  public ASTEqualOp(int id) {
    super(id);
  }

  public ASTEqualOp(Parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=ff89c26fa855e266e13c23d88649f83a (do not edit this line) */
