/* Generated By:JJTree: Do not edit this line. ASTEnd.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package yapl.compiler;

public
class ASTEnd extends SimpleNode {
  public ASTEnd(int id) {
    super(id);
  }

  public ASTEnd(Parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=25b97b134a7d8fc56648300cc2bf8fc5 (do not edit this line) */
