/* Generated By:JJTree: Do not edit this line. ASTFormalParamList.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY= */
package yapl.compiler;

public class ASTFormalParamList extends SimpleNode {
  public ASTFormalParamList(int id) {
    super(id);
  }

  public ASTFormalParamList(Parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=36825fcefab2d0169e6fbaafca139957 (do not edit this line) */
