/* Generated By:JJTree: Do not edit this line. ASTFormalParam.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package yapl.compiler;

public
class ASTFormalParam extends SimpleNode {
  public ASTFormalParam(int id) {
    super(id);
  }

  public ASTFormalParam(Parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=1d48f960d690200e7bb34e6b44e7988d (do not edit this line) */
