/* Generated By:JJTree: Do not edit this line. ASTFormalParam.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY= */
package yapl.compiler;

public class ASTFormalParam extends SimpleNode {
  public ASTFormalParam(int id) {
    super(id);
  }

  public ASTFormalParam(Parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=6e486f25ffd738b2274dd2d9cd3f4195 (do not edit this line) */
