/* Generated By:JJTree: Do not edit this line. ASTFormalParamList.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package yapl.compiler;

public
class ASTFormalParamList extends SimpleNode {
  public ASTFormalParamList(int id) {
    super(id);
  }

  public ASTFormalParamList(Parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=fb8b44d866973a514d7150240720bc09 (do not edit this line) */
