/* Generated By:JJTree: Do not edit this line. ASTIfStatement.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package yapl.compiler;

public
class ASTIfStatement extends SimpleNode {
  public ASTIfStatement(int id) {
    super(id);
  }

  public ASTIfStatement(Parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=321c21c71b6c78c9f20b6111cf6328aa (do not edit this line) */
