/* Generated By:JJTree: Do not edit this line. ASTMulOp.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY= */
package yapl.compiler;

public class ASTMulOp extends SimpleNode {
  public ASTMulOp(int id) {
    super(id);
  }

  public ASTMulOp(Parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=87fbf327cc7a820f071802e2ffdfbb39 (do not edit this line) */
