/* Generated By:JJTree: Do not edit this line. ASTMulOp.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package yapl.compiler;

public
class ASTMulOp extends SimpleNode {
  public ASTMulOp(int id) {
    super(id);
  }

  public ASTMulOp(Parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=8a71d1f5c12a7069b99ffa176577664c (do not edit this line) */
