/* Generated By:JJTree: Do not edit this line. ASTMulExpr.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package yapl.compiler;

public
class ASTMulExpr extends SimpleNode {
  public ASTMulExpr(int id) {
    super(id);
  }

  public ASTMulExpr(Parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=6fcb1967b4c5832191960aef5d907263 (do not edit this line) */
