/* Generated By:JJTree: Do not edit this line. ASTMulExpr.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY= */
package yapl.compiler;

public class ASTMulExpr extends SimpleNode {
  public ASTMulExpr(int id) {
    super(id);
  }

  public ASTMulExpr(Parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=1d2c64953b0aa1e4a4d5c6d9ec4c0918 (do not edit this line) */
