/* Generated By:JJTree: Do not edit this line. ASTNonArrayType.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package yapl.compiler;

public
class ASTNonArrayType extends SimpleNode {
  public ASTNonArrayType(int id) {
    super(id);
  }

  public ASTNonArrayType(Parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=75a5a086b9114dc404d7ab67da3ed5fc (do not edit this line) */
