/* Generated By:JJTree: Do not edit this line. ASTNonArrayType.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY= */
package yapl.compiler;

public class ASTNonArrayType extends SimpleNode {
  public ASTNonArrayType(int id) {
    super(id);
  }

  public ASTNonArrayType(Parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=4c44dc5af36dab69ca8c713ea42bdea1 (do not edit this line) */
