/* Generated By:JJTree: Do not edit this line. ASTProcedureCall.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package yapl.compiler;

public
class ASTProcedureCall extends SimpleNode {
  public ASTProcedureCall(int id) {
    super(id);
  }

  public ASTProcedureCall(Parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=d4f904025ac76521c24cb6f9c5187212 (do not edit this line) */
