/* Generated By:JJTree: Do not edit this line. ASTProgram.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY= */
package yapl.compiler;

public class ASTProgram extends SimpleNode {
  public ASTProgram(int id) {
    super(id);
  }

  public ASTProgram(Parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=c128c2ddbecca1be63f548dfb8d60122 (do not edit this line) */
