/* Generated By:JJTree: Do not edit this line. ASTPrimaryExpr.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY= */
package yapl.compiler;

public class ASTPrimaryExpr extends SimpleNode {
  public ASTPrimaryExpr(int id) {
    super(id);
  }

  public ASTPrimaryExpr(Parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=80515de440f4ae726377a5b3c7c37db6 (do not edit this line) */
