/* Generated By:JJTree: Do not edit this line. ASTProcedure.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY= */
package yapl.compiler;

public class ASTProcedure extends SimpleNode {
  public ASTProcedure(int id) {
    super(id);
  }

  public ASTProcedure(Parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=4258c83fdf55cceb1e72411688e6b0fc (do not edit this line) */
