/* Generated By:JJTree: Do not edit this line. ASTProcedure.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package yapl.compiler;

public
class ASTProcedure extends SimpleNode {
  public ASTProcedure(int id) {
    super(id);
  }

  public ASTProcedure(Parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=d49e28e99d0d904f8e573bb063649228 (do not edit this line) */
