/* Generated By:JJTree: Do not edit this line. ASTPrimaryExpr.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package yapl.compiler;

public
class ASTPrimaryExpr extends SimpleNode {
  public ASTPrimaryExpr(int id) {
    super(id);
  }

  public ASTPrimaryExpr(Parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=60cfb2aec3641eba7c7fff234febb16a (do not edit this line) */
