/* Generated By:JJTree: Do not edit this line. ASTProcedureCall.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY= */
package yapl.compiler;

public class ASTProcedureCall extends SimpleNode {
  public ASTProcedureCall(int id) {
    super(id);
  }

  public ASTProcedureCall(Parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=9a9d7798fd696760b7647aebe2d2a530 (do not edit this line) */
