/* Generated By:JJTree: Do not edit this line. ASTReturnType.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package yapl.compiler;

public
class ASTReturnType extends SimpleNode {
  public ASTReturnType(int id) {
    super(id);
  }

  public ASTReturnType(Parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=6778f805bb45c9270342415dd2cd9ead (do not edit this line) */
