/* Generated By:JJTree: Do not edit this line. ASTReturnStatement.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY= */
package yapl.compiler;

public class ASTReturnStatement extends SimpleNode {
  public ASTReturnStatement(int id) {
    super(id);
  }

  public ASTReturnStatement(Parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=b1051e26c480e07caeebc618c9521c3f (do not edit this line) */
