/* Generated By:JJTree: Do not edit this line. ASTRelExpr.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package yapl.compiler;

public
class ASTRelExpr extends SimpleNode {
  public ASTRelExpr(int id) {
    super(id);
  }

  public ASTRelExpr(Parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=88567f490bd9d5e8b8a8feb9b7825199 (do not edit this line) */
