/* Generated By:JJTree: Do not edit this line. ASTReturnStatement.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package yapl.compiler;

public
class ASTReturnStatement extends SimpleNode {
  public ASTReturnStatement(int id) {
    super(id);
  }

  public ASTReturnStatement(Parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=de3e3c7da03ac20e1fcaa24ff585f7b3 (do not edit this line) */
