/* Generated By:JJTree: Do not edit this line. ASTRelOp.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package yapl.compiler;

public
class ASTRelOp extends SimpleNode {
  public ASTRelOp(int id) {
    super(id);
  }

  public ASTRelOp(Parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=2e49ad0e1bd6165a9481844acbfaf082 (do not edit this line) */
