/* Generated By:JJTree: Do not edit this line. ASTRelExpr.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY= */
package yapl.compiler;

public class ASTRelExpr extends SimpleNode {
  public ASTRelExpr(int id) {
    super(id);
  }

  public ASTRelExpr(Parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=63d524f78aa6dd6af72f9001fc2163c6 (do not edit this line) */
