/* Generated By:JJTree: Do not edit this line. ASTRelOp.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY= */
package yapl.compiler;

public class ASTRelOp extends SimpleNode {
  public ASTRelOp(int id) {
    super(id);
  }

  public ASTRelOp(Parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=1da22ece1cad34a7658f73806932c285 (do not edit this line) */
