/* Generated By:JJTree: Do not edit this line. ASTReturnType.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY= */
package yapl.compiler;

public class ASTReturnType extends SimpleNode {
  public ASTReturnType(int id) {
    super(id);
  }

  public ASTReturnType(Parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=7af900a9a6dd6176c5b1141c120ee9fc (do not edit this line) */
