/* Generated By:JJTree: Do not edit this line. ASTStatementList.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY= */
package yapl.compiler;

public class ASTStatementList extends SimpleNode {
  public ASTStatementList(int id) {
    super(id);
  }

  public ASTStatementList(Parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=8303d2e121eff1eddef95368a4d87f48 (do not edit this line) */
