/* Generated By:JJTree: Do not edit this line. ASTSelector.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package yapl.compiler;

public
class ASTSelector extends SimpleNode {
  public ASTSelector(int id) {
    super(id);
  }

  public ASTSelector(Parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=8a7e7592a10a5dc93f065ff76d49e896 (do not edit this line) */
