/* Generated By:JJTree: Do not edit this line. ASTSelector.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY= */
package yapl.compiler;

public class ASTSelector extends SimpleNode {
  public ASTSelector(int id) {
    super(id);
  }

  public ASTSelector(Parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=dac78b3f8ed6011f1ea7ac780c353cca (do not edit this line) */
