/* Generated By:JJTree: Do not edit this line. ASTStatementList.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package yapl.compiler;

public
class ASTStatementList extends SimpleNode {
  public ASTStatementList(int id) {
    super(id);
  }

  public ASTStatementList(Parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=9f7bc24a5c79e74862e890efe725a1ca (do not edit this line) */
