/* Generated By:JJTree: Do not edit this line. ASTTypeDecl.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package yapl.compiler;

public
class ASTTypeDecl extends SimpleNode {
  public ASTTypeDecl(int id) {
    super(id);
  }

  public ASTTypeDecl(Parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=0b5a70fd105ba7da5bf54ef17bb2752a (do not edit this line) */
