/* Generated By:JJTree: Do not edit this line. ASTTypeDecl.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY= */
package yapl.compiler;

public class ASTTypeDecl extends SimpleNode {
  public ASTTypeDecl(int id) {
    super(id);
  }

  public ASTTypeDecl(Parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=ec78cc05b5113493d2d6e835efd209f0 (do not edit this line) */
