/* Generated By:JJTree: Do not edit this line. ASTUnaryExpr.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY= */
package yapl.compiler;

public class ASTUnaryExpr extends SimpleNode {
  public ASTUnaryExpr(int id) {
    super(id);
  }

  public ASTUnaryExpr(Parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=9ab55182f16dafc1444bcfd377dcbfa0 (do not edit this line) */
