/* Generated By:JJTree: Do not edit this line. ASTUnaryExpr.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package yapl.compiler;

public
class ASTUnaryExpr extends SimpleNode {
  public ASTUnaryExpr(int id) {
    super(id);
  }

  public ASTUnaryExpr(Parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=1cba36293f718adc7b631521c124c38a (do not edit this line) */
