/* Generated By:JJTree: Do not edit this line. ASTVarDecl.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY= */
package yapl.compiler;

public class ASTVarDecl extends SimpleNode {
  public ASTVarDecl(int id) {
    super(id);
  }

  public ASTVarDecl(Parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=73422a78a85f5323f511d61c65360a9c (do not edit this line) */
