/* Generated By:JJTree: Do not edit this line. ASTWhileStatement.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY= */
package yapl.compiler;

public class ASTWhileStatement extends SimpleNode {
  public ASTWhileStatement(int id) {
    super(id);
  }

  public ASTWhileStatement(Parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=9ea7c9ea4ba0a4c2eca8c9d30904ef95 (do not edit this line) */
