/* Generated By:JJTree: Do not edit this line. ASTWriteStatement.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package yapl.compiler;

public
class ASTWriteStatement extends SimpleNode {
  public ASTWriteStatement(int id) {
    super(id);
  }

  public ASTWriteStatement(Parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=01a966991b5251bef3dd8f1cb5fbce43 (do not edit this line) */
