/* Generated By:JJTree: Do not edit this line. ASTWriteStatement.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY= */
package yapl.compiler;

public class ASTWriteStatement extends SimpleNode {
  public ASTWriteStatement(int id) {
    super(id);
  }

  public ASTWriteStatement(Parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=c12cd42f127214d8104ed973cd63051f (do not edit this line) */
