/* Generated By:JavaCC: Do not edit this line. ParserTreeConstants.java Version 7.0.5 */
package yapl.compiler;

public interface ParserTreeConstants
{
  public int JJTPROGRAM = 0;
  public int JJTEND = 1;
  public int JJTDECL = 2;
  public int JJTCONSTDECL = 3;
  public int JJTVARDECL = 4;
  public int JJTTYPEDECL = 5;
  public int JJTNONARRAYTYPE = 6;
  public int JJTTYPE = 7;
  public int JJTRETURNTYPE = 8;
  public int JJTPROCEDURE = 9;
  public int JJTFORMALPARAMLIST = 10;
  public int JJTFORMALPARAM = 11;
  public int JJTSTATEMENTLIST = 12;
  public int JJTSTATEMENT = 13;
  public int JJTWRITESTATEMENT = 14;
  public int JJTRETURNSTATEMENT = 15;
  public int JJTWHILESTATEMENT = 16;
  public int JJTIFSTATEMENT = 17;
  public int JJTASSIGNMENT = 18;
  public int JJTPROCEDURECALL = 19;
  public int JJTARGUMENTLIST = 20;
  public int JJTBLOCK = 21;
  public int JJTEXPR = 22;
  public int JJTCREATIONEXPR = 23;
  public int JJTCONDANDEXPR = 24;
  public int JJTEQUALEXPR = 25;
  public int JJTRELEXPR = 26;
  public int JJTADDEXPR = 27;
  public int JJTMULEXPR = 28;
  public int JJTUNARYEXPR = 29;
  public int JJTPRIMARYEXPR = 30;
  public int JJTARRAYLEN = 31;
  public int JJTSELECTOR = 32;
  public int JJTLITERAL = 33;
  public int JJTRELOP = 34;
  public int JJTEQUALOP = 35;
  public int JJTADDOP = 36;
  public int JJTMULOP = 37;


  public String[] jjtNodeName = {
    "Program",
    "End",
    "Decl",
    "ConstDecl",
    "VarDecl",
    "TypeDecl",
    "NonArrayType",
    "Type",
    "ReturnType",
    "Procedure",
    "FormalParamList",
    "FormalParam",
    "StatementList",
    "Statement",
    "WriteStatement",
    "ReturnStatement",
    "WhileStatement",
    "IfStatement",
    "Assignment",
    "ProcedureCall",
    "ArgumentList",
    "Block",
    "Expr",
    "CreationExpr",
    "CondAndExpr",
    "EqualExpr",
    "RelExpr",
    "AddExpr",
    "MulExpr",
    "UnaryExpr",
    "PrimaryExpr",
    "ArrayLen",
    "Selector",
    "Literal",
    "RelOp",
    "EqualOp",
    "AddOp",
    "MulOp",
  };
}
/* JavaCC - OriginalChecksum=bcb19a4930f2ef76080def11c21bafb1 (do not edit this line) */
